# Generated by Django 4.0.1 on 2022-05-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorName', models.CharField(max_length=250)),
                ('BookName', models.CharField(max_length=250)),
                ('BookPublishedOn', models.CharField(max_length=250)),
                ('BookId', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Book_Table',
            },
        ),
    ]
